### ISSUE TITLE
How to use code to infer in my own data set? My own data set is not labeled, just want to see the actual application effect of HOI algorithm

### ISSUE THREAD

**Issue by ahong007007** [fredzzhang/spatially-conditioned-graphs#63]
thank you  for your work!

How to use code to infer in my own data set? My own data set is not labeled, just want to see the actual application effect of HOI algorithm.

thank you very much.

**Comment by fredzzhang** [comment]
Hi @ahong007007,

If you are only trying to run inference, it should be fairly simple. You can find the inference code [here](https://github.com/fredzzhang/spatially-conditioned-graphs/blob/main/diagnosis/demo.py). In particular, the data was loaded at line 125. Replace the three variables with your data, it should work.

```python
125    image, detection, target = dataset[args.index]
```

In terms of the format, if I remember correctly, `image` is a 3d tensor with shape [3, H, W], `detection` is a dictionary with detected bounding boxes, labels and scores. Since your custom data is not labelled, you can set `target` to `None`.

Try printing out those three variables to see the detailed data format.

Fred.
