### ISSUE TITLE
Trained model on VCOCO

### ISSUE THREAD

**Issue by fangruizhu** [fredzzhang/spatially-conditioned-graphs#77]
Hi, could you provide the trained model on VCOCO dataset? I didn't find a download link.

Thanks.

**Comment by fangruizhu** [comment]
I trained the model and only got 50.39 mAP for scenario-1 on VCOCO dataset, which is inconsistent with the reported 54.2 in the paper.

**Comment by fredzzhang** [comment]
Hi @fangruizhu,

The computed average precision includes a class (point-instr) that does not correspond to valid human-object interactions, which has been excluded from the final performance as a convention. To get the true performance, a simple way is to multiply the computed value by 25 and then divide by 24.

The reported mAP (`54.2`) is obtained using fine-tuned Faster R-CNN, not the pre-trained one. We didn't release those detections because you can simply get better detections using the [fine-tuned DETR](https://github.com/fredzzhang/hicodet/tree/main/detections#train-and-test-detr-on-hico-det).

Fred.

**Comment by fangruizhu** [comment]
Thanks for the reply!
